---
- hosts: localhost
  gather_facts: no
  vars:
    input: "{{ lookup('file', '../real.txt').split('\n') }}"
    vectors: []
    intersections: 0
  tasks:
    - name: Cook inputs.
      include_tasks: clean-vector.yml
      loop: "{{ input }}"

    - name: Make a copy of the vectors.
      set_fact:
        vectors2: "{{ vectors }}"

    - include_tasks: intersect-outer-loop.yml
      loop: "{{ vectors }}"
      loop_control:
        loop_var: v1

    - name: At how many points do at least two lines overlap?
      debug:
        msg: "{{ intersections }}"
